backend:
  name: git-gateway
  branch: main # update if you use a different default branch

media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "artists"
    label: "Artists"
    folder: "_posts"
    extension: "md"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Name" }
      - {
          name: "resident",
          label: "Resident",
          widget: "boolean",
          default: true,
        }
      - { name: "instagram", label: "Instagram" }
      - { name: "thumbnail", label: "Thumbnail", widget: "image" }
      - { name: "email", label: "Email", widget: "string", required: false }
      - {
          name: "galleryImages",
          label: "Gallery Images",
          widget: "list",
          field: { name: "image", label: "Image", widget: "image" },
          required: false,
        }
      - { name: "body", label: "Bio", widget: "markdown" }

  - name: "events"
    label: "Events"
    files:
      - name: "events-gallery"
        label: "Events Gallery"
        file: "_data/events.json"
        fields:
          - {
              name: "images",
              label: "Event Images",
              widget: "list",
              field: { name: "image", label: "Image", widget: "image" },
            }

  - name: "studio"
    label: "Studio"
    files:
      - name: "studio-gallery"
        label: "Studio Gallery"
        file: "_data/studio.json"
        fields:
          - {
              name: "images",
              label: "Studio Images",
              widget: "list",
              field: { name: "image", label: "Image", widget: "image" },
            }
